 repos:
  - repo: local
    hooks:
      - id: black
        name: "Black: Checking code style"
        entry: black
        language: system
        types: [python]
      - id: isort
        name: "Isort: Checking imports sorting"
        entry: isort
        language: system
        types: [python]
