 repos:
  - repo: local
    hooks:
      - id: black
        name: "Black: Checking code style"
        entry: black --check
        language: system
        types: [python]
      - id: flake8
        name: "Flake8: Checking code quality"
        entry: flake8
        language: system
        types: [python]
      - id: isort
        name: "Isort: Checking imports sorting"
        entry: isort --check-only
        language: system
        types: [python]
